version: '3.9'

volumes:
    mysql-db: {}

services:
    ts_mysql:
        image: mysql
        env_file: .env
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-u", "$MYSQL_USER", "-p$MYSQL_PASSWORD"]
            timeout: 5s
            interval: 5s
            retries: 3
        networks:
            - ts_apps
        volumes:
            - mysql-db:/var/lib/mysql
        command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
        restart: always

    ts_app_web_python:
        build: ./
        env_file: .env
        ports:
            - '2000:80'
        depends_on:
            ts_mysql:
                condition: service_healthy
        volumes:
            - ./.:/var/www
        networks:
            - ts_apps

networks:
    ts_apps:
        name: ts_apps
        driver: bridge
